### ISSUE TITLE
Default cx_Oracle parameters

### ISSUE THREAD

**Issue by sinys15** [GoodManWEN/cx_Oracle_async#11]
Hello,
1) Sometimes I have got cx_Oracle.DatabaseError: ORA-24422
I want to use FORCE parameter of SessionPool.close(force=False) for to make it true.
https://cx-oracle.readthedocs.io/en/latest/api_manual/session_pool.html
Could you please add this option.

2) cx_Oracle.SessionPool defaults is  encoding=None, nencoding=None
Could you please make it as original values.

**Comment by GoodManWEN** [comment]
Not much experience developing a wrapper of a  db connecter , thanks for your contribute.

About question one , while I'm testing with the following code after set `force` to `True` , there comes another oracle error:
```Python
import asyncio
import cx_Oracle_async

async def query(pool):
    # query for 10s
    conn = await pool.acquire()
    cursor = await conn.cursor()
    await cursor.execute("BEGIN  DBMS_LOCK.SLEEP(:a); END;",(10,))

async def main():
    dsn = cx_Oracle_async.makedsn(host = 'localhost' , port = '1521' , service_name = 'orcl')
    pool = await cx_Oracle_async.create_pool(user='', password='',dsn = dsn)
    loop = asyncio.get_running_loop()
    loop.create_task(query(pool))
    await asyncio.sleep(2)
    await pool.close(force = True)
    print("Done")

asyncio.run(main())
```

Error traceback:
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<conn() done, defined at C:\cx_Oracle_async\test.py:4> exception=DatabaseError(<cx_Oracle._Error object at 0x00000208E303A270>)>
Traceback (most recent call last):
  File "C:\cx_Oracle_async\test.py", line 8, in conn
    await cursor.execute("BEGIN  DBMS_LOCK.SLEEP(:a); END;",(10,))
  File "C:\cx_Oracle_async\cx_Oracle_async\cursors.py", line 25, in execute
    return await self._loop.run_in_executor(self._thread_pool , self._cursor.execute , sql , *args , **kwargs)
cx_Oracle.DatabaseError: DPI-1010: not connected

Done
[Finished in 10.4s]
```

Could you please tell me the normal reaction of the same behaviour in the original cx_Oracle threading mode, will it raise another exception or it will be completely silent and all exceptions will be handled by the framework itself? And will the main thread continues at time point 2s or time point 10s.

**Comment by sinys15** [comment]
> Not much experience developing a wrapper of a db connecter
Me too. I have got the same error from your example but I noticed that it take all 10 seconds before it really finished and may be it really no connections on close(True) step. May be we have to check SessionPool.busy or SessionPool.opened.

**Comment by GoodManWEN** [comment]
I've tested same functional code in thread mode , looks like it gives out the same result (exception) in the same situation.

```Python
import cx_Oracle
import threading
import time

def fetch_in_10s(pool):
    conn = pool.acquire()
    cursor = conn.cursor()
    cursor.execute("BEGIN  DBMS_LOCK.SLEEP(3); END;")
    pool.release(conn)
    return 'Done'

dsn = cx_Oracle.makedsn(host = 'localhost' , port = '1521' , service_name = 'orcl')
pool = cx_Oracle.SessionPool(user='', password='',dsn = dsn)
t = threading.Thread(target = fetch_in_10s , args = (pool , ))
t.start()
time.sleep(2)
pool.close(force = True)
time.sleep(5 - 2)
```
Error traceback:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\test.py", line 20, in fetch_in_10s
    cursor.execute("BEGIN  DBMS_LOCK.SLEEP(3); END;")
cx_Oracle.DatabaseError: DPI-1010: not connected
[Finished in 6.3s]
```

Which means we can easily add parameter `force` to `pool.close()` ,but you'll get an exception raised anyhow. So I guess maybe there's something wrong with your business code , since with using context manager to make sure connection proper released , there should not be a connection still running at the time connection pool close in normal `await` use. Could you show a simplified model make error recurrence.

**Comment by GoodManWEN** [comment]
I've uploaded a new dev branch , in which the framework explicit call `connection.cancel()` to interrupt a activate connection. Which may behave more like the orignal cx_Oracle lib , that will get a faster return (do not have to wait until current query finish) in the main threadloop , but won't get rid of an Exception. Maybe you can do some test in your enviorment.  Personally I'm not satisfied with this implementation , cause I find it's impossible to get running connection from `cx_Oracle.SessionPool` object ， thus I have to make some weird hacking to track with the opening connections.

**Comment by sinys15** [comment]
> t = threading.Thread(target = fetch_in_10s , args = (pool , ))
> t.start()
> time.sleep(2)
> pool.close(force = True)

I have tried repeat your example and I have got next exeption:
cx_Oracle.OperationalError: ORA-01013
It is basic exeption for situation when you break statement executing. It's OK.

If you increase  time.sleep(2) for 5 sec and do the same pool.close(force = True) you wouldn't get DPI or ORA exception.
It works right.

**Comment by GoodManWEN** [comment]
I've tested several times and the result various ,sometimes I got `ORA-01013` and sometimes `DPI-1010`.

If that's the proper behaviour , you should try the latest dev branch , it will be the same.

Remaining one unexpected bug is , if I explicit call `connection.calcel()` in asyncio when a connection is doing some query , I'll got two other lines of `ORA-06512` exception besides `ORA-01013`:
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<query() done, defined at C:\cx_Oracle_async\test.py:13> exception=OperationalError(<cx_Oracle._Error object at 0x000001EAB3FBFE40>)>
Traceback (most recent call last):
  File "C:\cx_Oracle_async\test.py", line 21, in query
    await cursor.execute("BEGIN  DBMS_LOCK.SLEEP(:a); END;",(13,))
  File "C:\cx_Oracle_async\cx_Oracle_async\cursors.py", line 24, in execute
    return await self._loop.run_in_executor(self._thread_pool , self._cursor.execute , sql , *args , **kwargs)
cx_Oracle.OperationalError: ORA-01013: user requested cancel of current operation
ORA-06512: at "SYS.DBMS_LOCK", line 215
ORA-06512: at line 1

Main thread continue.
[Finished in 6.4s]
```

Good news is the other two exceptions will not cause any trouble to the main threadloop.

**Comment by GoodManWEN** [comment]
For the other problem you mentioned in the original post , I think there's something wrong with the official doc's description on `nencoding` parameter.

If I modify code in create_pool like this:
```Python
def create_pool(
        ...
        encoding=None,
        nencoding=None, 
        ...
    ):
    coro = _create_pool(
        ...
        encoding=encoding, 
        nencoding=nencoding,
        ...
    )
    return AsyncPoolWrapper_context(coro)
```

I'll get an error message:
```
Traceback (most recent call last):
  File "C:\cx_Oracle_async\test.py", line 39, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\cx_Oracle_async\test.py", line 30, in main
    pool = await cx_Oracle_async.create_pool(user='SCOTT', password='',dsn = dsn)
  File "C:\cx_Oracle_async\cx_Oracle_async\utils.py", line 31, in _create_pool
    pool = cxor.SessionPool(dsn=dsn, **kwargs)
TypeError: argument 13 must be str, not None
```

Where argument 13 is `nencoding`.
`encoding` works fine with default value None.

**Comment by sinys15** [comment]
Actually using **nencoding** is not often situation, **encoding** is desirable. But somebody should make issue about **nencoding**  for cx_Oracle developers :)

Now I don't know how can I return connection to the pool?
conn1 = await oracle_pool1.acquire()

And how can I close the conn1 without close all pool?

**Comment by GoodManWEN** [comment]
So I'm not going to invite nencoding option currently.

There seems to be no explicit means to close a valid connection , all I did is explicitly cancel running query in connection before close the whole pool.

**Comment by sinys15** [comment]
I mean it will be good to support SessionPool.release(connection, tag=None) method.

**Comment by GoodManWEN** [comment]
Uh , In this sense the release method was switched to connection cause I consider it easier to use if you need only a conn object and without pool , when you would like to release.
e.g.
```Python
async with create_pool('','',dsn) as pool:
    conn = await pool.acquire()
    # do some thing
    conn.release()
```

Maybe it's better to support also a interface to pool object? However I'm not sure if the connection will be closed when you release it from pool , it's more likely just going back into pool and keep connecting in the background waiting for another thread to require.

**Comment by sinys15** [comment]
Of course will be better to have all methods for different situations :)
SessionPool.release
SessionPool.drop
connection.release

**Comment by GoodManWEN** [comment]
@sinys15 May I ask your oracle version.

Codes of `connection.cancel()` performs well on my develop platform , however it got trouble on CI after push commit. I find it would make the query never return instead of terminate it immediately and throw an exception  when I call method `cancel()`. The only difference between the two platfroms is I'm using newer version of oracle 19c with develop , the test server of CI runs a 11g version(cause that's the only image avilable on docker hub),  I speculate that previous version of oracle donot support well with cx_Oracle's `connection.cancel()`?

**Comment by sinys15** [comment]
19
From your example I randomly got 
cx_Oracle.DatabaseError: ORA-12155: TNS
 or
cx_Oracle.OperationalError: ORA-01013

In my opinion ORA-01013 is correct for this situation.

**Comment by GoodManWEN** [comment]
Okay , seems got a pretty awkward situation here , let me take time to think of how to implement properly.

First of all the default value of encoding and nencoding cannot be set to None due to cx_Oracle donot accept value type other than string at the begining.

In the second place , A explicit `connection.cancel()` have to be trigger before `sessionPool.close(force = True)` otherwise the force close will not run properly in asyncio (which performs differently with same code in thread module for unknown reason), where main thread will stay no response.

Further, if we implement a explicit connection.cancel in force close mode , it works basicly fine with oracle 19 , but may not support previous version , for example those code make oracle connection thread no response in oracle 11g. So that if a new release drafted under the latest dev branch wholly intact , it will only support server version of 19 and will lead to bug in some situation , and that's not what I as a maintainer expect.

**Comment by GoodManWEN** [comment]
Finally decide to add a new parameter `interrupt` to let user decide whether force cancel running query before session pool closed. In the latest implementation you can get immediate return if you use `pool.close(force = True , interrupt = True)` no matter if there's  running query on Oracle database version 19 or later , in the mean time if runs on a version before 11 , the main thread will no longer go on until all query finished if you call `pool.close(force = True , interrupt = False)`.

For special case `pool.close(force = True , interrupt = True)` on legacy versions will cause a never-stop bug.I'm going to close this issue.
