### ISSUE TITLE
Support connection with dsn

### ISSUE THREAD

**Issue by sinys15** [GoodManWEN/cx_Oracle_async#5]
Could you please add create_pool function with dsn parameter.
And it looks better to use cx_Oracle.makedsn to build dsn string instead of your variant "f"{host}:{port}/{db}"".
Example from documentation:
dsn = cx_Oracle.makedsn("dbhost.example.com", 1521, service_name="orclpdb1")
connection = cx_Oracle.connect("hr", userpwd, dsn, encoding="UTF-8")

**Comment by sinys15** [comment]
async def create_pool(user = 'system', password = '', host = 'localhost', port = '1521', db = 'orcl', dsn = None, loop = None, minsize = 2, maxsize = 4, encoding = 'UTF-8', autocommit=False):
    if loop == None:
        loop = asyncio.get_running_loop()
    if dsn == None:
        dsn = csor.makedsn(host=host, port=port, service_name=db)
    pool = csor.SessionPool(user=user, password=password, dsn=dsn, min=minsize, max=maxsize, increment=1, threaded=True, encoding=encoding)
    pool = AsyncPoolWarpper(pool)
    await pool.preexciting()
    return pool

**Comment by GoodManWEN** [comment]
@sinys15 Thanks for correcting my stuppid spelling mistakes. I'm considering whether to change parameter name 'db' into 'service_name'. The reason why I choose 'db' is at that moment I hope it to be more painless for user switching between mysql and oracle db api in python's async universe. However I find it very different between mysql and oracle db ,as example , the 'db' option in current code means very different from mysql's database on concept , which actually means a identifier of oracledb's listener service but not any kind of database or tablespace.

And if we give up holding same api concept with aiomysql , it's better to add sid option either. What‘s your point of view?

**Comment by sinys15** [comment]
My point of view is Oracle DB too much specific and it's be better do not change cx_Oracle behavior.
The original SessionPool specification is:

cx_Oracle.SessionPool(user=None, password=None, dsn=None, min=1, max=2, increment=1, connectiontype=cx_Oracle.Connection, threaded=False, getmode=cx_Oracle.SPOOL_ATTRVAL_NOWAIT, events=False, homogeneous=True, externalauth=False, encoding=None, nencoding=None, edition=None, timeout=0, waitTimeout=0, maxLifetimeSession=0, sessionCallback=None, maxSessionsPerShard=0)

https://cx-oracle.readthedocs.io/en/latest/api_manual/module.html#cx_Oracle.SessionPool
And it's better to keep this agreement and don't change it to mySQL way.
There are several ways (Oracle DB ways) how you can specify connection. It's all described
https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html

**Comment by GoodManWEN** [comment]
New branch was drafted at [dev](https://github.com/GoodManWEN/cx_Oracle_async/tree/73ed700038e110f0bf15913caee1875b75647fcb), you can checkout if that's fine

**Comment by GoodManWEN** [comment]
Btw , find it seems to be a slight faster switching to dsn connection mode , is that's what it should be like , or its just cause by some testing inaccuracy.

**Comment by sinys15** [comment]
If you specify SID you can don't specify host and port. This parameters takes from tnsnames. Thats why specify default host and port in function specification can be not good.

**Comment by GoodManWEN** [comment]
You mean like this? `dsn = cx_Oracle_async.makedsn(sid = 'somesid')`

**Comment by sinys15** [comment]
No, I mean don't set it
async def create_pool(
...
        host='localhost',
        port='1521',
        service_name='orcl',
by default. This should be user choice.

**Comment by GoodManWEN** [comment]
I set default value of host , port ,service_name , sid  to None and merged dev branch. Besides , new unit test added , so that it maybe easier to PR for other developers. I'll close this issue.

btw I find it necessary to make 'Advanced Queuing' available , mentioned in one of your previous issue , if I'd like to use functions such as dbms_lock.sleep(). No ideas how to implement though.

**Comment by sinys15** [comment]
I have no experience how to make it (AQ) async. Now I use execute method with dbms_aq.Enqueue and dbms_aq.Dequeue in PL/SQL block.
You can use it like cursor.execute('begin dbms_lock.sleep(3); end;')

You have to pay attention that sleep and Dequeue freeze process for setted time and you have to use something like asyncio.Task(self.process_dequeue_async()) for to make it async. But will be better investigate async libraries like aio_pika for rabbit or analog for postgres.

**Comment by GoodManWEN** [comment]
Server CI uploaded to Github Marketplace , feel free to use. [https://github.com/marketplace/actions/setup-oracle-11g-server](https://github.com/marketplace/actions/setup-oracle-11g-server)
