### ISSUE TITLE
Async Close procedure for Oracle pool

### ISSUE THREAD

**Issue by sinys15** [GoodManWEN/cx_Oracle_async#6]
Seems like the Close method of Oracle pool is missed for async.
I'm not shure is it just
```
    async def close_connection_async(self) -> None:
        if self._connection:
            await self._connection.close()
```
or should be like
```
    async def close_connection_async(self) -> None:
        if self._connection:
            self._connection.close()
            await self._connection.wait_closed()
```

**Comment by sinys15** [comment]
Please add:
class **AsyncPoolWrapper**:
```
    async def close(self):
        await self._loop.run_in_executor(self._thread_pool , self._pool.close)
```

**Comment by GoodManWEN** [comment]
@sinys15 Done. I agree with it's better to implement a whole shutdown of connection pool but not lead in exceptions to allow connection close itself.

The reason why I didnot implement a shutdown before seems to be I find it no problem at all not doing graceful shutdown.

**Comment by sinys15** [comment]
Thank you. Could you please don't forget to increase library version with changes.

**Comment by GoodManWEN** [comment]
Due to theres still unfinished issue remain , Im not going to release a new version to pypi immediately.
